### ISSUE TITLE
Issue when running, model.py missing?

### ISSUE THREAD

**Issue by SandroLuck** [SoftWiser-group/CoDiSum#1]
```
 python CopyNetPlusgen.py


Using TensorFlow backend.
Traceback (most recent call last):
  File "CopyNetPlusgen.py", line 1, in <module>
    from models1 import CopyNetPlus
  File "/home/sluck/eth/CoDiSum/models1.py", line 10, in <module>
    from models import combined_loss
ModuleNotFoundError: No module named 'models'
```

I think there is a file missing, or from which package should combined_loss come?
Thanks in advance

**Comment by KingGoldXu** [comment]
You can simply comment `from models import combined_loss` out.
This statement is from older version, it‘s outdated.

**Comment by SandroLuck** [comment]
sidenote: one also has to create a folder models, after this everything works

**Comment by KingGoldXu** [comment]
Thanks, I will update README!
