### ISSUE TITLE
BLEU和Meteor怎么测的

### ISSUE THREAD

**Issue by xwh130** [SoftWiser-group/CoDiSum#4]
您好，我最近在研究commit message生成问题，通过您的代码没有得到论文里的结果，想问一下metrics具体是怎么测的

**Comment by KingGoldXu** [comment]
我们使用了[Jiang等人工作](https://ieeexplore.ieee.org/abstract/document/8115626)中的代码，meteor是使用jar包计算的，bleu是使用perl脚本
[metric_material.zip](https://github.com/SoftWiser-group/CoDiSum/files/8529442/metric_material.zip)

**Comment by xwh130** [comment]
收到，感谢回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SoftWiser-group/CoDiSum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SoftWiser-group/CoDiSum] BLEU和Meteor怎么测的 (Issue #4)





 
我们使用了Jiang等人工作中的代码，meteor是使用jar包计算的，bleu是使用perl脚本
 metric_material.zip
