### ISSUE TITLE
How can we build your data files from Jiang and MacMillan dataset

### ISSUE THREAD

**Issue by soroushjavdan** [SoftWiser-group/CoDiSum#5]
Thanks for sharing your interesting work.
I know that you included the data file in your repo. However, since I want to know each commit's project, I wonder if it would be possible for you to explain how I can build the data file you included in the repo from Jiang and MacMillan dataset (the 1k java repo which you used)?
I already check the data_process_tools.py and data4CopynetV3.py and found that you were passing '/commitgen/ASE_commitgen_data/ASEdata_filterd_100.json' file to the build function which I was not able to find in the repo.
Thanks in advance.

**Comment by KingGoldXu** [comment]
The `ASEdata_filterd_100.json` is the same as (subset of) Jiang and MacMillan dataset but in json format.

**Comment by soroushjavdan** [comment]
Thanks for your quick reply @KingGoldXu .
I wonder if there is any way for me to have access to the JSON version of the Jiang and MacMillan dataset since I want to run the build() function in [data4CopynetV3.py](https://github.com/SoftWiser-group/CoDiSum/blob/master/data4CopynetV3.py) and save the dataset with extra information.
Your help will be much appreciated.

**Comment by soroushjavdan** [comment]
Thanks for your help again @KingGoldXu 
I was reading the code and I am not sure which file I should use to regenerate your dataset ( Data4CopynetV3.py or data_process_tools.py)! That would be great if you could clarify that. 
Also, I wonder if you could provide the JSON format file of the Jiang and MacMillan dataset which your code will use as input.
